### ISSUE TITLE
Not getting a refresh_token

### ISSUE THREAD

**Issue by wminkstein** [zquestz/omniauth-google-oauth2#16]
I'm using version 0.1.9

My line in my devise.rb is the following:

```config.omniauth :google_oauth2, GOOGLE_KEY, GOOGLE_SECRET, 
{:scope=>"https://www.google.com/m8/feeds, 
https://www.googleapis.com/auth/userinfo.email, 
https://www.googleapis.com/auth/userinfo.profile", :approval_prompt=>""} 

```
I'm intentionally not setting :access_type and it should default to "offline"

When I get a response back I am logging out the result of:  request.env['omniauth.auth']

and I am not seeing any refresh token.  Here is the credentials part of that response:

```

credentials:
  token: xxx
  expires_at: 1329093395
  expires: true

```
```
